### ISSUE TITLE
Nodemon included in dependencies

### ISSUE THREAD

**Issue by nmunro** [RomanHyde/BethanysPieAPI#5]
Hey Roman, had a quick look at the project and you have nodemon installed as part of the dev dependencies, as we discussed in class it forms part of the devDependencies.

You can fix it by reinstalling it with

npm install nodemon --save-dev

You also have a start script that directly depends on nodemon, which would fail if you do the above and try to deploy to a service like heroku.

I would suggest you rename your start rule to dev which you can run with:

npm run dev

Since you are running a development build locally, and write a start rule that will simply run:

node index.js 

Just a couple of things I noticed in the package.json as I was having a wee look at your project.

**Comment by RomanHyde** [comment]
Hey Niel! Thanks for taking a look at the project for me.
You are right about the nodemon dependancies, woopsie! I'll get that fixed up.
I feel like running through this has definately helped.

**Comment by RomanHyde** [comment]
I updated it here, hopefully, this is okay.
https://github.com/RomanHyde/BethanysPieAPI/blob/implement-cors/package.json
